DATASET:
  PATH: "datasets/TESCAN/2x2"
  TILE_OVERLAP: 0.3
STITCHER:
  OUTPUT_PATH: "output/TESCAN-optimised-grid"
  RESOLUTION_RATIO: 0.5
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "euclidean"
  CONSTRUCTION_METHOD: "optimised"
  COMPOSITING_METHOD: "overwrite"
  OPTICAL_FLOW_REFINEMENT: True
  OPTICAL_FLOW_REFINEMENT_TYPE: "grid"
  COLORED_OUTPUT: True
  NORMALISE_INTENSITY: True
LOFTR:
  CHECKPOINT_PATH: "LoFTR/weights/demis_ds.ckpt"
