DATASET:
  PATH: "datasets/DEMIS"
  TILE_OVERLAP: 0.3
STITCHER:
  OUTPUT_PATH: "output/DEMIS-pretrained-optimised"
  RESOLUTION_RATIO: 0.5
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "euclidean"
  CONSTRUCTION_METHOD: "optimised"
  COMPOSITING_METHOD: "overwrite"
  COLORED_OUTPUT: False
  NORMALISE_INTENSITY: True
LOFTR:
  CHECKPOINT_PATH: "LoFTR/weights/outdoor_ds.ckpt"
