DATASET:
  PATH: "datasets/EM424"
  TILE_OVERLAP: 0.3
STITCHER:
  OUTPUT_PATH: "output/EM424-optimised-pretrained"
  RESOLUTION_RATIO: 0.5
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "euclidean"
  CONSTRUCTION_METHOD: "optimised"
  COMPOSITING_METHOD: "overwrite"
  OPTICAL_FLOW_REFINEMENT: True
  OPTICAL_FLOW_REFINEMENT_TYPE: "grid"
  COLORED_OUTPUT: False
  NORMALISE_INTENSITY: True
LOFTR:
  CHECKPOINT_PATH: "LoFTR/weights/outdoor_ds.ckpt"
EVAL:
  SPLIT_PATH: "datasets/EM424/splits/test_list.txt"
