DATASET:
  PATH: "datasets/DEMIS"
  TILE_OVERLAP: 0.3
STITCHER:
  RESOLUTION_RATIO: 1.0
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "euclidean"
  CONSTRUCTION_METHOD: "optimised"
  COMPOSITING_METHOD: "overwrite"
LOFTR:
  CHECKPOINT_PATH: "LoFTR/weights/outdoor_ds.ckpt"
EVAL:
  SPLIT_PATH: "datasets/DEMIS/splits/test_list.txt"
